### ISSUE TITLE
TopStats visible only for logged in users in the forum

### ISSUE THREAD

**Issue by AlexL777** [dmzx/phpBB-3.2-Top-Stats#1]
Hello Developers,

I would like to use your TopStats Extension permanently, but unfortunately the right permissions are missing, so that the TopStats are also displayed for logged off users.

Will you still realize this or how can I handle it better?

Thanks in advance.

**Comment by dmzx** [comment]
For now there is no permmission in, but look at the https://github.com/dmzx/phpBB-3.2-Top-Stats/blob/master/styles/prosilver/template/recent_active_body.html#L1  S_USER_LOGGED_IN and the last ENDIF in that file.
If you delete that and clear cache it will display to guests.
Also for top_stats_body.html file.

**Comment by AlexL777** [comment]
Thanks for your quick help and that has everything worked. I will have this Repo now by Fork also in my Github account display and forgive you here already times a star :smile:
